apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: product-customizer
  description: The Product Customizer component can be used on the Product Details
    Page (PDP) to display attachments and/or a subscription form.
  tags:
    - typescript
    - react:16
  annotations:
    vtex.com/janus-acronym: ""
    vtex.com/o11y-os-index: ""
    grafana/dashboard-selector: ""
    github.com/project-slug: vtex-apps/product-customizer
    vtex.com/platform-flow-id: ""
    backstage.io/techdocs-ref: dir:../
    vtex.com/application-id: HWAPG7IL
spec:
  system: store-framework-ui-apps
  lifecycle: stable
  owner: te-0013
  type: frontend-ui
  dependsOn: []
  subcomponentOf: store-framework
