import ProductAssemblyOptionItemChildrenDescription from './components/ProductAssemblyOptions/ProductAssemblyOptionItemChildrenDescription'

export default ProductAssemblyOptionItemChildrenDescription
