export const baseOptions: Record<string, ItemAssembly> = {
  '2000584': {
    id: '2000584',
    seller: '1',
    options: [
      {
        id: 'add-on_Add-on',
        name: 'add-on',
        type: 'MULTIPLE',
        inputValues: [],
        required: true,
        composition: {
          minQuantity: 0,
          maxQuantity: 3,
          items: [
            {
              id: '2000590',
              minQuantity: 0,
              maxQuantity: 1,
              priceTable: 'vip',
              price: 6000,
              seller: '1',
              initialQuantity: 0,
            },
            {
              id: '2000589',
              minQuantity: 0,
              maxQuantity: 1,
              priceTable: 'vip',
              price: 9000,
              seller: '1',
              initialQuantity: 0,
            },
            {
              id: '2000590',
              minQuantity: 0,
              maxQuantity: 1,
              priceTable: 'vip',
              price: 6000,
              seller: '1',
              initialQuantity: 0,
            },
          ],
        },
      },
      {
        id: 'text_style_Text Style',
        name: 'text_style',
        type: 'SINGLE',
        required: true,
        inputValues: [],
        composition: {
          minQuantity: 1,
          maxQuantity: 1,
          items: [
            {
              id: '2000591',
              minQuantity: 0,
              maxQuantity: 1,
              priceTable: 'vip',
              price: 0,
              seller: '1',
              initialQuantity: 1,
            },
            {
              id: '2000592',
              minQuantity: 0,
              maxQuantity: 1,
              priceTable: 'vip',
              price: 1500,
              seller: '1',
              initialQuantity: 0,
            },
          ],
        },
      },
      {
        id: 'engraving_Engraving',
        name: 'engraving',
        type: 'TOGGLE',
        required: true,
        inputValues: [],
        composition: {
          minQuantity: 0,
          maxQuantity: 1,
          items: [
            {
              id: '2000586',
              minQuantity: 0,
              maxQuantity: 1,
              priceTable: 'vip',
              price: 2600,
              seller: '1',
              initialQuantity: 0,
            },
            {
              id: '2000587',
              minQuantity: 0,
              maxQuantity: 1,
              priceTable: 'vip',
              price: 3000,
              seller: '1',
              initialQuantity: 0,
            },
          ],
        },
      },
    ],
  },
  '2000587': {
    id: '2000587',
    seller: '1',
    options: [],
  },
  '2000592': {
    id: '2000592',
    seller: '1',
    options: [],
  },
  '2000591': {
    id: '2000591',
    seller: '1',
    options: [],
  },
  '2000590': {
    id: '2000590',
    seller: '1',
    options: [],
  },
  '2000589': {
    id: '2000590',
    seller: '1',
    options: [],
  },
  '2000586': {
    id: '2000586',
    seller: '1',
    options: [
      {
        id: '1-3-lines',
        name: '1-3-lines',
        type: 'MULTIPLE',
        required: false,
        inputValues: [
          {
            label: 'Line 1',
            maxLength: 200,
            type: 'TEXT',
            domain: null,
            defaultValue: '',
          },
          {
            label: 'Line 2',
            maxLength: 200,
            type: 'TEXT',
            domain: null,
            defaultValue: '',
          },
          {
            label: 'Line 3',
            maxLength: 200,
            type: 'TEXT',
            domain: null,
            defaultValue: '',
          },
        ],
        composition: null,
      },
    ],
  },
}
